#cloud-config
autoinstall:
  version: 1
  identity:
    realname: 'Alysson Gleyson'
    hostname: AlyssonPC-Ubuntu
    username: alysson
    password: $crypted_pass
  locale: pt_BR.utf8
  keyboard:
    layout: br
    timezone: "America/Recife"
