#cloud-config
autoinstall:
  version: 1
  identity:
    realname: 'Alysson Gleyson'
    hostname: AlyssonPC-Ubuntu
    username: alysson
    password: $crypted_pass
  locale: pt_BR.utf8
  keyboard:
    layout: br
  timezone: "America/Recife"
  packages:
    - libreoffice
    - wget
    - gdebi
    - rar
    - unrar
  snaps:
    - name: brave
      channel: stable
    - name: obsidian
      channel: stable
  codecs:
      install: true
  drivers:
    install: true
  updates: all
  shutdown: reboot
